# Generated by Django 2.2 on 2021-03-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymaster',
            name='NetPrAr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
