# Generated by Django 2.2 on 2021-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210327_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgmaster',
            name='Rate',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='Url',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='accountId',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='address',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='city',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='lwPropertyId',
        ),
    ]
