# Generated by Django 2.2 on 2021-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210327_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgmaster',
            name='acres',
        ),
        migrations.RemoveField(
            model_name='avgmaster',
            name='price',
        ),
    ]
