# Generated by Django 2.2 on 2021-03-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210327_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgmaster',
            name='UserPercentage',
            field=models.FloatField(default=0.0),
        ),
    ]
