# Generated by Django 2.2 on 2021-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avgmaster_userpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgmaster',
            name='FinaleValue',
            field=models.FloatField(default=0.0),
        ),
    ]
