# Generated by Django 2.2 on 2021-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_avgmaster_finalevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgmaster',
            name='Rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
