# Generated by Django 2.2 on 2021-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_avgmaster_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgmaster',
            name='Descrpt',
            field=models.TextField(default='!', max_length=255),
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='Url',
            field=models.URLField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='accountId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='acres',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='adTargetingCountyId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='baths',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='beds',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='brokerCompany',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='brokerName',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='city',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='cityID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='companyLogoDocumentId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='countyId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='description',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='hasHouse',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='hasVideo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='hasVirtualTour',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='imageAltTextDisplay',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='imageCount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='isALC',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='isHeadlineAd',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='lwPropertyId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='status1',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='types',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avgmaster',
            name='zip',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
